#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define HIGH 60
#define WIDTH 60
#define ROADWITHCOIN 2
#define WALL 1
#define PACMAN 4
#define ROAD 3
#define ENEMY 5
#define NUMBEROFENEMYS 10
#define PACMANSEARCH 6
#define POWERUP 7
#define NUMBEROFPOWERUPS 20
#define USEDWAY 8
#define PACMANDETECTIONRANGE 20
#define LOWERWALL 9
#define NUMBEROFLOWWALLS 10
#define SHOTRANGE 8
#define SHOT 10

#endif
